feed/urls.py
from django.urls import path

from .views import HomePageView,PostDetailView,PostFormView
app_name = 'feed'
urlpatterns=[
    path('',HomePageView.as_view(),name='index'),
    path('info/<int:pk>/',PostDetailView.as_view(),name="detail"),
    path('post/',PostFormView.as_view(),name='post')
]


    

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import include
from feed import urls as feed_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(feed_urls, namespace='feed')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

feed/models.py
from django.db import models
from sorl.thumbnail import ImageField

class Post(models.Model):
    text=models.CharField( max_length=150,blank=False,null=False)
    image=models.ImageField()
    def __str__(self):
        return self.text
    

# Create your models here.

feed/forms.py
from django import forms

class PostForm(forms.Form):
    image=forms.FileField()
    text=forms.CharField(label="Department")

feed/views.py
from django.views.generic import TemplateView,DetailView,FormView
from .models import Post
from django.contrib import messages


from .forms import PostForm
class HomePageView(TemplateView):
    template_name='home.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["posts"] = Post.objects.all()
        return context
    
class PostDetailView(DetailView):
    template_name="detail.html"
    model=Post


class PostFormView(FormView):
    template_name='new_post.html'
    form_class=PostForm
    success_url='/'
    
    def get(self, request, *args, **kwargs):
        self.request=request
        return super().get(self, request, *args, **kwargs)
    
    def form_valid(self, form):
        new_object=Post.objects.create(text=form.cleaned_data['text'],image=form.cleaned_data['image'])
        messages.add_message(self.request,messages.SUCCESS,'You successfully posted')
        return super().form_valid(form)
    

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</head>
<body>
    {%include "navbar.html" %}

    {% if messages %}
        {% for message in messages %}
        <div class="bg-{% if message.tags %}{{ message.tags }}{% else %}success{% endif %} bg-gradient text-center text-white py-4">{{message}}</div>
        {% endfor %}
    {% endif %}
<div class="container" >
    {%block body%}
    {%endblock%}
</div>
</body>
</html>

templates/detail.html
{%extends "base.html" %}
{%block title%}detail view {%endblock%}
{%block body%}
<div class="row">
    <div class="col-sm-10 offset-sm-1">
        <h2>{{object.text}}</h2>
        <img src="{{ object.image.url}}"  class="img-fluid" />
    </div>
</div> 
{%endblock%}

templates/home.html
{%extends "base.html" %}
{% load thumbnail %}
{% block title %}home{%endblock%}
{%block body %}
    <div class="row">
        {%for post in posts%}
            <div class="col-sm-6 col-md-4">
                <div class="card m-3" style="width: 18rem;">
                    {% thumbnail post.image "200x200" crop="center" as im %}
                        <img src="{{ im.url }}" class="card-img-top" alt="...">
                    {% endthumbnail %}
                    <div class="card-body">
                        <p class="card-text">{{post.text}}</p>
                        <a href="{% url 'feed:detail' post.id %}" class="btn btn-primary">Show image</a>
                    </div>
                </div>
            </div>
            
            
        {%empty%}
        <div class="col-sm-6 offset-3 text-center my-5 p-3">
            <h2>Welcome!</h2>
            <a href="{% url 'feed:post'%}" class="btn btn-success text-white">Upload an image</a>
        </div>
        {%endfor%}
    </div>
{%endblock%}

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary px-5">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Photo books</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{%url 'feed:index'%}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'feed:post'%}">New post</a>
          </li>

        </ul>
      </div>
    </div>
  </nav>

templates/new_post.html
{%extends "base.html" %}
{%block title%}post view {%endblock%}
{%block body%}
<div class="row">
<form  action="" method="POST" enctype="multipart/form-data" class="col-sm-8 offset-4 my-5">
    {% csrf_token %}
    <h2>Upload Image</h2>
    {{form.as_p}}
<button type="submit" class="btn btn-success btn-lg " >submit</button>

{%endblock%}